# Generated by Django 6.0 on 2025-12-10 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matwanacore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matwanauser',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('conductor', 'Conductor'), ('sacco', 'Sacco Admin'), ('admin', 'Matwana Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending Review'), ('Suspended', 'Suspended')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'sacco'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_saccos', to='matwanacore.matwanauser', verbose_name='Sacco Administrator')),
            ],
        ),
        migrations.AddField(
            model_name='matwanauser',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='matwanacore.sacco'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sacco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='matwanacore.sacco'),
        ),
    ]
